spring:
  application:
    name: LIMITSERVICE

eureka:
  client:
    enabled: false

### SWAGGER CONFIG ###    
swagger: 
  title: OTT Limits Service API
  version: 1.0
  description: Remittance Limits Service
  base-package: 
  contact: 
    name: snmaddula
    url: 
    email: snmaddula@gmail.com